{
 "title": "Fluent Bit Prometheus Metrics Plugin",
 "time": { "from": "now-5h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Web response time (Linear Histogram Demo)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fluentbit_origin_lin_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fluentbit_origin_lin_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(fluentbit_origin_lin_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Web response time (Exponential Histogram Demo)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fluentbit_origin_exp_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fluentbit_origin_exp_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(fluentbit_origin_exp_elapsed_duration_usec_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "rate of change origin total by method (Counter Demo)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_origin_total[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Logs ingested by origin (Summary Demo)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_syslog_summary_sum) by (origin)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "Total Logs ingested (1 GiB Gauge Demo)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gauge_message_byte_count" }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"syslog\"}"
    }
   ]
  }
 ]
}